### ISSUE TITLE
Server.doc

### ISSUE THREAD

**Issue by Vincentmask** [PSU-MCECS-SAFE/SAFE#41]
**1**. The server is using the Express.js framework with the following line of code: `const app = express();`.

**2**. The server is using the CORS middleware to allow cross-origin requests to the Express.js application from any domain, with the following line of code: `app.use(cors())`;. However, this approach is only recommended for development environments. In production, you should change each endpoint's CORS settings to the specific URL. For example, if you want to restrict a **GET request** for a **"Receiver"** endpoint to a specific URL, you can use the following pseudoCode snippet:
```
// Set up CORS with the allowed origin set to "http:/feedback.cs.pdx.edu"
// This means that requests from any other origin will be rejected by default.
app.use(cors({
  origin: 'http://feedback.cs.pdx.edu'
}));

// Define the route handler for the /api/users endpoint
app.get('/getAllMessage', (req, res) => {
  // Only allow requests from "http:/feedback.cs.pdx.edu/receiver"
  if (req.headers.origin !== 'http:/feedback.cs.pdx.edu/receiver') {
    return res.status(403).json({ error: 'Forbidden' });
  }

  // Handle GET request 
  ...
});
```     
**3**. The server has a POST request with the endpoint /addMessage that is used to insert messages into the database. It first gets all the data from the request URL body and stores them in different objects. Then, it sanitizes the body to prevent XSS attacks using the xss package. After that, it replaces anything that is not a letter, number, or '/' from the title. The server then tries to connect to the database and makes a query to insert the message based on the data we got from the URL body. Finally, it sends out an email using the spawn package and writes the title and message body in the email.

**4. 1** The following code snippet is used to make the server listen to the IP address' port:
```
const port = 3001;
app.listen(port, '131.252.208.28', () => {
  console.log(`Server listening on port ${port}`);
});
```

**4. 2** In the production environment in the VM, here is what you need:
```
app.listen(3001, 'feedback.cs.pdx.edu', () => {
  console.log(`Server listening on port 3001`);
});
```

**5. 1** When using the fetch API on the UI, the following code snippet can be used to send a request to the server's endpoint, catch the response, and any errors from the endpoint:
```
fetch(`http://131.252.208.28:${port}/addMessage`, {method, header, body})
  .then(response => response.json())
  .then(data => console.log(data))
  .catch(error => console.error(error));
```

**5. 2** In the production environment in the VM, here is what you need:
```
fetch(`https://feedback.cs.pdx.edu/addMessage`, {method, header, body})
  .then(response => response.json())
  .then(data => console.log(data))
  .catch(error => console.error(error));
```
**This is because CAT set a proxy on the addMessage URL. And now we only have the addMessage proxy available. If you need to add more endpoints to fetch from it. CONTACT CAT**

**Comment by Vincentmask** [comment]
[server.test](https://github.com/PSU-MCECS-SAFE/SAFE/blob/MVP/src/tests/server.test.tsx)
FYI, we are not able to make a test on the server, because we are only having one POST endpoint.

The problem is if we want to test it, we can only insert a message into the database, and we **can not delete it after the test is done** because in the MVP we don't have the unique code version available.

**Workflow of testing server**
1. If the unique code is deployed in the future. We can basically insert a message with a code we manually create(e.g. a 65-byte code, because our code now is 32~64 byte) to the database to test the **POST REQUEST**. By this, we know this is the test message we are going to play with. Now we can expect a status of 200 to indicate message had been sent to db.
2. Then we can test the **GET REQUEST** by querying the 65-byte code and expect a 200 response.
3. Then we can use the **PUT REQUEST** the edit the message based on querying the 65-byte code and then alter the message we want. Then maybe query the message that been edited to see if we do have this message. By then we tested the edit feature of the server.
4. Then we test the **DELETE REQUEST**, by simply deleting the corresponding code message, expect a 200 response status as well.
5. Then we can test the **GET REQUEST** again to query the 65-byte code to see if the message is gone by expect the response status to be 404 (or something else that you wrote in your get request error section).

**Comment by imOnVacation** [comment]
closed since its in doc
